define

## Only used in the following rule. It's the same as a treatment, except that it requires a certain
# numbers of papers documenting the connection
referenced-treatment sub relationship
  relates target
  relates therapy;

referencedTreatments sub rule
when {
  $cancer isa cancer;
  $sl isa stem-loop;
  (disease: $cancer, affected: $sl) isa interaction  has degree >= 4;
  $m isa mature;
  (precursor: $sl, matured: $m) isa mirna-precursor;
  $gene isa gene;
  (targeting-mirna: $m, targeted-gene: $gene) isa gene-target has degree >= 4;
  (influenced: $gene, chemical: $drug) isa action; $drug isa drug;
}

then {
  (target: $cancer, therapy: $drug) isa referenced-treatment;
};

