insert


$inferMature isa inference-rule
 lhs
 {$z isa cancer;
  $a isa stem-loop;
  (disease: $z, affected: $a);
  $b isa mature;
  (precursor: $a, matured: $b);}
 rhs
 {(disease: $z, affected: $b) isa interaction;};

 $inferGene isa inference-rule
 lhs
 {$z isa cancer;
  $a isa mature;
  (disease: $z, affected: $a);
  $b isa gene;
  (targeting-mirna: $a, targeted-gene: $b);}
 rhs
 {(disease: $z, affected: $b) isa interaction;};

$inferCancerDrug isa inference-rule
lhs {
  (disease: $c, affected: $g);
  (influenced: $g, chemical: $d);
}
rhs {
  (target: $c, therapy: $d) isa treatment;
};
