define


inferMature sub rule
when
 {$z isa cancer;
  $a isa stem-loop;
  (disease: $z, affected: $a);
  $b isa mature;
  (precursor: $a, matured: $b);}
 then
 {(disease: $z, affected: $b) isa interaction;};

inferCancerDrug sub rule
when {
  (disease: $c, affected: $b);
  (targeting-mirna: $b, targeted-gene: $g);
  (influenced: $g, chemical: $d);
}
then {
  (target: $c, therapy: $d) isa treatment;
};
